service: serverless-flask


plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-offline

custom:
  wsgi:
    app: sanic_app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1


functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'